export const GET_USER_PUBLIC_REPOSITORIES = "GET_USER_PUBLIC_REPOSITORIES";
export const GET_USER_PUBLIC_REPOSITORY = "GET_USER_PUBLIC_REPOSITORY";
export const GET_USER_REPOSITORY_README = "GET_USER_REPOSITORY_README";
export const GET_BRITO_LAST_UPDATED_REPOSITORIES = "GET_BRITO_LAST_UPDATED_REPOSITORIES";
export const GET_BRITO_PROFILE = "GET_BRITO_PROFILE";
